### ISSUE TITLE
Echanger sur un sujet

### ISSUE THREAD

**Issue by sun-tea** [Hypertopic/Vitraux-Experts#1]
Un utilisateur créé le sujet avec un 1er post. Il peut rajouter une (des) ressource(s) associée(s) à son sujet.
Tous les utilisateurs peuvent répondre, et voter la pertinence du post ainsi que ses réponses.

**Comment by benel** [comment]
À la fois trop vague ("un utilisateur", "un sujet", "un post", "une ressource"), trop sur le "comment", pas assez sur le "qui", le "pourquoi", le "quoi".

Essayez de raconter une petite histoire qui donne envie de financer, d'utiliser, ou de participer au projet.

**Comment by mellenguyen** [comment]
Périmètre de l'application et fonctionnement basique imaginée :

L'application cherche à faciliter l'échange entre experts des vitraux. Les experts ciblés sont typiquement des enseignants, des chercheurs, des professionnels comme des guides touristiques ou des vitraillistes, des étudiants en histoire, etc. L'application pourrait ainsi regrouper une communauté autour du même thème : les vitraux. L'application se veut référence dans le domaine, et pour cela elle se servira des données fournies par sa communauté.

M. Dupont, ancien professeur d'histoire, regrette le manque de détails et d'informations en ligne sur un des vitraux d'une baie de l'Eglise de Villenauxe. Il créé un nouveau sujet intitulé "Vitrail de la Vierge Marie - Baie 1 - Eglise de Villenauxe" dans l'application web, détaillant dans son post initial ses interrogations sur l'interprétation de l'histoire narré par ce vitrail. L'application, grâce aux informations fournies dans le titre, va lui suggérer de rajouter en ressources liées au sujet les photographies et documents déjà présents dans la base. Il rajoute les ressources proposées, et joint également des fichiers locaux.
Mme. Raisin, guide touristique de la région, apporte un nouveau document tiré d'un ouvrage issu des archives de la ville de Villenauxe, éclaircissant l'histoire du vitrail. Sa réponse reçoit des retours approbateurs d'autres utilisateurs (+8 votes), ainsi que des commentaires approuvant le post. Le document fourni par Mme. Raisin est dorénavant, grâce à l'approbation des autres, disponible dans la base des ressources existantes, et sera visible à la recherche sur les mots "Villenauxe".
