### ISSUE TITLE
Commenter un vitrail

### ISSUE THREAD

**Issue by sun-tea** [Hypertopic/Vitraux-Experts#17]
- [x] Manuel : Grégoire Peterschmitt,TROUBLAT Damien
- [x] Test de recette EK, Patrick LIM
- [x] Implémentation Etienne JACQUOT

Un expert peut apporter des informations, une question, etc sur un vitrail en étant sur la page de celui-ci.

**Comment by hervelito** [comment]
_Cas d'un commentaire initial (premier) sur la page d'un vitrail indéterminé:_

Visiter la page d'accueil des **EXPERT VITRAUX APP**
Cliquer sur Vitraux Indéterminés
Dans la page des vitraux affichés saisir/cliquer sur **SNZ 104** (Maquette manquante)
Cliquer sur le bouton "Commenter" (Manquant sur la maquette)
Saisir un texte 
Valider le texte saisi 
Vérifier que le texte saisi est présent sur la page

Cas du commentaire d'un commentaire déjà présente sur la page 
(Pré-réquis: commentaire usr le vitrail déjà)

Visiter la page d'accueil des **EXPERT VITRAUX APP**
Cliquer sur Vitraux Indeterminés
Dans la page des vitraux affichés, saisir/cliquer sur **SNZ 104** (Maquette manquante)
Pour un commentaire donné sur la page, cliquer sur le bouton "Répondre"
Saisir le commentaire avec des informations pertinentes dans zone indiquée
Valider le commentaire saisi
Verifier que le commentaire est bien présent sur la page

**Comment by HommeGrenouille** [comment]
Une des fonctionnalités principales de cette application est de pouvoir ajouter des commentaires dans la fiche d’un vitrail afin de permettre une communication entre les membres de la communauté Vitraux-Expert.
Par ces commentaires, on peut donner un point de vue, poser une question, ou répondre à celles d’autres membres.

	Pour commenter un vitrail, il faut se placer sur la fiche du vitrail, cela peut être fait via la page d’accueil, ou le menu déroulant. Les commentaires se trouvent dans la partie inférieure droite de la page. 
	Pour écrire un nouveau commentaire, il suffit de cliquer dans un boite de dialogue vide et de le saisir. Une fois ce dernier terminé, il faut cliquer sur “Envoyer”.
	Votre commentaire apparaît donc à la suite des commentaires précédents. 

Vous pouvez aussi choisir de répondre à un commentaire en particulier, en séléctionnant “Répondre” sous le commentaire correspondant.

Nous encourageons fortement l’ajout de références pour justifier tout point de vue présenté dans les commentaires; elles permettent de valoriser votre commentaire aux yeux des autres utilisateurs.
Pour ajouter une référence, il existe une icône en bas à droite d’une boîte de dialogue. Lorsqu’on clique dessus, un nouveau champ texte apparaît dans lequel on peut insérer un lien, ou une autre référence.

**Comment by HommeGrenouille** [comment]
Une des fonctionnalités principales de cette application est de pouvoir ajouter des commentaires dans la fiche d’un vitrail afin de permettre une communication entre les membres de la communauté Vitraux-Expert.
Par ces commentaires, on peut donner un point de vue, poser une question, ou répondre à celles d’autres membres.

Pour commenter un vitrail, il faut se placer sur la fiche du vitrail, cela peut être fait via la page d’accueil, ou le menu déroulant. Les commentaires se trouvent dans la partie inférieure droite de la page. 
Pour écrire un nouveau commentaire, il suffit de cliquer dans un boite de dialogue vide et de le saisir. Une fois ce dernier terminé, il faut cliquer sur “Envoyer”.
Votre commentaire apparaît donc à la suite des commentaires précédents. 

Vous pouvez aussi choisir de répondre à un commentaire en particulier, en séléctionnant “Répondre” sous le commentaire correspondant.

Nous encourageons fortement l’ajout de références pour justifier tout point de vue présenté dans les commentaires; elles permettent de valoriser votre commentaire aux yeux des autres utilisateurs.
Pour ajouter une référence, il existe une icône en bas à droite d’une boîte de dialogue. Lorsqu’on clique dessus, un nouveau champ texte apparaît dans lequel on peut insérer un lien, ou une autre référence.

**Comment by HommeGrenouille** [comment]
Une des fonctionnalités principales de cette application est de pouvoir ajouter des commentaires dans la fiche d’un vitrail afin de permettre une communication entre les membres de la communauté Vitraux-Expert.
Par ces commentaires, on peut donner un point de vue, poser une question, ou répondre à celles d’autres membres.

Pour commenter un vitrail, il faut se placer sur la fiche du vitrail en cliquant sur l'image correspondante. Les commentaires se trouvent dans la partie inférieure droite de la page. 
Pour écrire un nouveau commentaire, il suffit de cliquer dans un boite de dialogue vide et de le saisir. Une fois terminé, il faut cliquer sur “Envoyer”.
Le commentaire écrit apparaît donc à la suite des commentaires précédents. 

Vous pouvez aussi choisir de répondre à un commentaire en particulier, en séléctionnant “Répondre” sous le commentaire correspondant.

Nous encourageons fortement l’ajout de références pour justifier tout point de vue présenté dans les commentaires; elles permettent de valoriser votre commentaire aux yeux des autres utilisateurs.
Pour ajouter une référence, il existe une icône en bas à droite d’une boîte de dialogue. Lorsqu’on clique dessus, un nouveau champ texte apparaît dans lequel on peut insérer un lien, ou une autre référence.

Les commentaires sont affiché par ordre chronologique, sauf si vous répondez spécifiquement à un commentaire précédemment écrit.

**Comment by qpierre** [comment]
Test du bug
