### ISSUE TITLE
Consulter la fiche d'un vitrail

### ISSUE THREAD

**Issue by sun-tea** [Hypertopic/Vitraux-Experts#18]
- [ ] Manuel
- [ ] Test de recette
- [ ] Implémentation

Un expert peut accéder à la fiche d'un vitrail sur la page d'accueil du site, via les listes défilantes "Vitraux les plus vus" et "Derniers vitraux modifiés"

**Comment by hervelito** [comment]
![scan maquette-page-001](https://cloud.githubusercontent.com/assets/17782012/14914192/64450f12-0e08-11e6-8de2-fd1244ad9ade.jpg)

**Comment by mellenguyen** [comment]
![scan maquette-page-004](https://cloud.githubusercontent.com/assets/6019103/14914319/49709d90-0e09-11e6-9f2f-045479047fd8.jpg)
