### ISSUE TITLE
Evaluer un commentaire

### ISSUE THREAD

**Issue by sun-tea** [Hypertopic/Vitraux-Experts#21]
- [ ] Manuel
- [ ] Test de recette
- [ ] Implémentation

Sur la fiche d'un vitrail, l'expert peut donner son opinion sur la véracité/utilité d'un commentaire en lui attribuant un point ou en enlevant un.

**Comment by vautrinr** [comment]
En cliquant sur une flèche vertical, qui va soit de haut en bas, ou de bas en haut, l'utilisateur peut respectivement enlever ou donner un point à un commentaire.

Chaque commentaire et fiche de vitrail a son propre système de point.
