### ISSUE TITLE
Indiquer un problème sur un vitrail

### ISSUE THREAD

**Issue by sun-tea** [Hypertopic/Vitraux-Experts#22]
- [x] Manuel : Elsa Bassi, Quentin Pierre
- [x] Test de recette : Elsa Bassi, Grégoire Peterschmitt
- [ ] Implémentation

**Comment by mellenguyen** [comment]
![scan maquette-page-003](https://cloud.githubusercontent.com/assets/6019103/14914282/0db7b626-0e09-11e6-99d3-de069c9fb87a.jpg)

**Comment by ElsaBassi** [comment]
Pour indiquer un problème sur un vitrail, l'expert doit se rendre tout d’abord sur la page d’accueil. Après avoir cliqué sur une photo de vitrail qui l’intéresse, il arrive sur la fiche du vitrail.
Sur chaque champ du vitrail se trouve un drapeau de signalement. En cas de données qui nous semble incorrectes concernant un champ, on peut choisir de cliquer sur le drapeau. On peut également écrire un commentaire pour ajouter une précision sur le signalement.

Si un vitrail est signalé, il se retrouve dans la catégorie “Données incorrectes” et il est alors visible en tant que tel sur la page d’accueil. 

D’autres utilisateurs peuvent alors voir tous les signalements des vitraux. Ils peuvent confirmer un problème ou indiquer que le signalement est incorrect en répondant au commentaire. Le débat peut débuter autour de la question posée par l’expert.
