### ISSUE TITLE
Améliorer des informations sur un vitrail

### ISSUE THREAD

**Issue by sun-tea** [Hypertopic/Vitraux-Experts#23]
- [x] Manuel
- [ ] Test de recette
- [ ] Implémentation

**Comment by mellenguyen** [comment]
![scan maquette-page-003](https://cloud.githubusercontent.com/assets/6019103/14914241/d2fe9e78-0e08-11e6-9bca-045852139d13.jpg)

**Comment by vautrinr** [comment]
https://docs.google.com/document/d/1UVld1S6dndw6PP4Bi54PAKPW7Znq1BQqohS5F4HS2fQ/edit?usp=sharing

**Comment by etiennej70** [comment]
L'amélioration des informations a lieu sur la plateforme hypertopic directement par un "administrateur" et non directement depuis l'application Facebook.
Je marque en "invalid".
Le manuel rédigé correspond + à "Consulter la fiche d'un vitrail" non ?
