### ISSUE TITLE
Ajouter une nouvelle ressource

### ISSUE THREAD

**Issue by kayanyim** [Hypertopic/Vitraux-Experts#3]
Un utilisateur rajoute une nouvelle ressource.
Il rajoute les descriptions correspondantes à la ressource.
Un administrateur va alors valider l'authenticité de la description et de la ressource.
La ressource est ensuite rajouter à la base de données.

**Comment by benel** [comment]
Ceci ressemble plutôt à une fonctionnalité (et encore il resterait beaucoup de travail pour se rapprocher du vocabulaire et des intérêts des usagers).
Par ailleurs, la gouvernance des données que vous proposez est très discutable : qu'est-ce qui vous laisse penser que "l'administrateur" est plus légitime que l'expert pour évaluer la qualité de la description ?
