### ISSUE TITLE
Afficher les informations associées à un vitrail

### ISSUE THREAD

**Issue by chivaa** [Hypertopic/Vitraux-Experts#84]
- [x] Scénario
- [x] Tests de Recette 
  - [x] Tests de Recette IHM
  - [x] Tests de Recette WS
- [x] Maquette
- [x] Implémentation
  - [x] Implémentation Back-End
  - [x] Implémentation Front-End

Afficher le vitrail et les informations associées à celui-ci quand on clique dessus

**Comment by Ludoutt** [comment]
maquette 👍 
![image](https://cloud.githubusercontent.com/assets/7795028/26196589/b1892214-3bbf-11e7-829c-bb1f6d9bd4f4.png)

**Comment by Ludoutt** [comment]
Exemple d'appel de l'API pour récupérer les infos d'un vitrail : 
http://localhost:3000/api/corpus/Vitraux%20-%20B%C3%A9nel/0105eaada11cf24bc10d723c48ef6ab11d15880f

**Comment by Ludoutt** [comment]
Exemple d'appel de l'API pour récupérer les infos d'un  point de vue : http://localhost:3000/api/viewpoint/56e092d8a6179a788c74b618b29801c0
