### ISSUE TITLE
Consulter l'historique de la restauration d'un vitrail

### ISSUE THREAD

**Issue by sbargash** [Hypertopic/Vitraux-Experts#88]
- [x] Scénario
- [ ] Tests de Recette 
- [ ] Maquette
- [ ] Implémentation

Cette fonctionnalité permettra l'affichage de l'ensemble des restauration effectuées sur un vitrail

**Comment by Shyked** [comment]
(je copie/colle ce commentaire sur les issues / PR concernées)

L'application ne permettra pas la "restauration" à proprement parler.
Si j'ai bien compris, ton idée était de découper les révisions d'un vitrail en plusieurs "restaurations", c'est à dire qu'on considère qu'une restauration engendra la modification des attributs d'un vitrail, voire l'ajout d'un nouveau vitrail.
On a pas prévu de découper le révisions en "restauration" pour l'instant, si tu as une idée à ce sujet là ça pourrait être bien qu'on en discute d'abord (on pourrait faire ça demain, le 12/05).

En revanche, c'était bien de soulever le fait qu'on a pas de feature pour créer un nouveau vitrail, un détail très important !
