### ISSUE TITLE
Ajouter / [Modifier] un commentaire sur un vitrail

### ISSUE THREAD

**Issue by bahnane** [Hypertopic/Vitraux-Experts#94]
- [x] Scénario
- [x] Tests de Recette 
  - [x] Tests de Recette IHM
  - [x] Tests de Recette WS
- [x] Maquette
- [x] Implémentation
  - [x] Implémentation Back-End
  - [x] Implémentation Front-End

En tant qu'utilisateur, je peux ajouter un commentaire sur un vitrail, et au besoin le modifier ou le supprimer.

**Comment by bahnane** [comment]
![94 ajouter-modifier-supprimer commentaire sur un vitrail](https://cloud.githubusercontent.com/assets/6776133/26029281/6c5c44be-3831-11e7-9496-afce9de6367e.png)

**Comment by bahnane** [comment]
![94 ajouter-modifier-supprimer commentaire sur un vitrail](https://cloud.githubusercontent.com/assets/6776133/26029292/ba7eefc0-3831-11e7-94be-7e415b5c36c5.png)

**Comment by Ludoutt** [comment]
code disponible dans le back end 👍 
(POST) ITEM_comment : /corpus/comment with body {id_item: varchar, id_corpus: varchar, id_user: varchar, text: varchar}
(GET) ITEM_comments : /corpus/Vitraux - Bénel/00745c3e27d91d00e3d4db33828dd8797e9c2195/comment
