### ISSUE TITLE
Consulter la liste des vitraux

### ISSUE THREAD

**Issue by Ludoutt** [Hypertopic/Vitraux-Experts#96]
- [x] Scénario
- [x] Tests de Recette 
  - [x] Tests de Recette IHM
  - [x] Tests de Recette WS
- [x] Maquette
- [x] Implémentation
  - [x] Implémentation Back-End
  - [x] Implémentation Front-End

Cette fonctionnalité permet d'afficher la liste de tous les vitraux présents sur la plateforme

**Comment by Ludoutt** [comment]
- [ ] Scénario
- [ ] Tests de Recette 
- [ ] Maquette
- [ ] Implémentation

**Comment by Ludoutt** [comment]
maquette dispo : https://utt.mybalsamiq.com/mockups/5827394.png?key=6dbd49f0d630b678620365de9c174f02a06087b5

![image](https://cloud.githubusercontent.com/assets/7795028/26195539/711e1e4e-3bbc-11e7-8008-728de4fb35b6.png)

**Comment by Ludoutt** [comment]
Ex : d'entrée de l'API à utiliser pour obtenir la liste des items d'un corpus : http://localhost:3000/api/corpus/Vitraux%20-%20B%C3%A9nel/0105eaada11cf24bc10d723c48ef6ab11d15880f

**Comment by boironpi** [comment]
Le lien ne marche pas, c'est quoi ?

**Comment by Ludoutt** [comment]
le lien est à utiliser sur la machine locale, une fois le projet d'API lancé ;)
